# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6aee23b912d82837053b7956a0cce8688317ccc55f0839d5a01e6b489bbbb3ea032e0b50c46f4a8312d0da850de94885695f4a121d8e77197634ac38934e7a09

test:
  secret_key_base: 184e7e344daa7f7bd4a5ff5f7127a4ea4e303b050b61ac7ec1a4cfb922594822d0ad7926abf145c0dac19ca525587e675a13d87da44f54ea92cb28e6477f5c52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
